version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres-2DAM-V
    restart: always
    environment:
      POSTGRES_DB: gamermood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gamermood"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
